const string = 'Lorem ipsum dolor, sit amet consectetur adipisicing elit. Totam dolor velit quas soluta dicta sunt nesciunt repellendus quia error minus assumenda, autem animi esse rem suscipit ut quaerat deserunt inventore.';

console.log(reducer(string, 'upperCase')); // => LOREM IPSUM....
console.log(reducer(string, 'lowerCase')); // => lorem ipsum....
console.log(reducer(string, 'capitalize'));// => Lorem Ipsum....
